<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>OrderProcessing.BuildingBlocks</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Serilog.AspNetCore" />
  </ItemGroup>

</Project>
